name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the Snake animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg

      # Commit and push the Snake animation
      - name: Commit and Push Snake Animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated Snake animation"
          file_pattern: dist/snake.svg